modLoader="javafml"
loaderVersion="[39,)"
license="Custom"
# issueTrackerURL=""

[[mods]]
modId="endofminecraft"
version="1.0.0"
displayName="End of Minecraft"
# updateJSONURL=""
# displayURL=""
# logoFile=""
authors="Willatendo"
description='''
A mod that makes the world of Minecraft a nuclear wasteland.
'''

[[dependencies.endofminecraft]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.endofminecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.endofminecraft]]
    modId="tyrannotitanlib"
    mandatory=true
    versionRange="[3.1.0,)"
    ordering="NONE"
    side="BOTH"